remote_theme: pages-themes/midnight@v0.2.0


title: Sivu /w Jekyll teema
author:
  name: Miikka Saukkonen
  
description: Hello World! Tervetuloa sivulle. Feel free to connect /w me in LinkedIn :)

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  
social_links:
  - { platform: linkedin,       user_url: "www.linkedin.com/in/miikkasaukkonen" }

