title: Page /w Jekyll theme - MS
description: Tervetuloa sivulle!
remote_theme: digitalmalayali/linkhub-jekyll-theme

# Site Configuration
name: Sivu /w Jekyll theme - MS 
tagline: Hello World, tervetuloa sivulle!  
description: A free, open-source Jekyll link-in-bio theme.  # Also used as a meta description
locale: fi_FI 
