title: Page /w Jekyll theme - MS
description: Tervetuloa sivulle!
remote_theme: benbalter/retlab

# Linkki linkkariin.
contact_links:
  - name: LinkedIn
    url: www.linkedin.com/in/miikkasaukkonen
    icon: linkedin
    

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
