remote_theme: pages-themes/midnight@v0.2.0


title: Sivu /w Jekyll teema
author:
  name: Miikka Saukkonen
  
description: Hello World! Tervetuloa sivulle.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme


