remote_theme: digitalmalayali/linkhub-jekyll-theme

# Site Configuration
name: Sivu /w Jekyll teema - MS 
tagline: Hello World, tervetuloa sivulle!  
description: Feel free to connect /w me :) 
locale: fi_FI 

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    
